// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCA9c9fPqw6jXpm_aqjVxPLRVLH9MSRLk',
    appId: '1:961912087799:android:57e1b9f839ec838d94dff2',
    messagingSenderId: '961912087799',
    projectId: 'rotaapp-63a25',
    storageBucket: 'rotaapp-63a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVxZjZ5q10yP7EMyn3BNQouqMCvbS1V7U',
    appId: '1:961912087799:ios:1edf888c720bca9394dff2',
    messagingSenderId: '961912087799',
    projectId: 'rotaapp-63a25',
    storageBucket: 'rotaapp-63a25.firebasestorage.app',
    iosBundleId: 'com.example.rotaapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0iNySkMP6aUwkY-6EZIjSZMdGaDj2KlI',
    appId: '1:961912087799:web:2760c7effb4a222e94dff2',
    messagingSenderId: '961912087799',
    projectId: 'rotaapp-63a25',
    authDomain: 'rotaapp-63a25.firebaseapp.com',
    storageBucket: 'rotaapp-63a25.firebasestorage.app',
    measurementId: 'G-G7W1SRW627',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVxZjZ5q10yP7EMyn3BNQouqMCvbS1V7U',
    appId: '1:961912087799:ios:1edf888c720bca9394dff2',
    messagingSenderId: '961912087799',
    projectId: 'rotaapp-63a25',
    storageBucket: 'rotaapp-63a25.firebasestorage.app',
    iosBundleId: 'com.example.rotaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0iNySkMP6aUwkY-6EZIjSZMdGaDj2KlI',
    appId: '1:961912087799:web:d2956e97b63ddd3e94dff2',
    messagingSenderId: '961912087799',
    projectId: 'rotaapp-63a25',
    authDomain: 'rotaapp-63a25.firebaseapp.com',
    storageBucket: 'rotaapp-63a25.firebasestorage.app',
    measurementId: 'G-4C5P4F85TP',
  );

}