name: rotaapp # Bu uygulamanın dart paket adıdır, görünen ad değil.
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.1.2
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  provider: ^6.1.1
  uuid: ^4.0.0
  url_launcher: ^6.2.4
  cupertino_icons: ^1.0.2
  collection: ^1.17.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Uygulama simgesi (Launcher Icon) paketi zaten ekli
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # Uygulama içindeki görsel varlıkları buraya eklemeye devam edin
  assets:
    - assets/images/arkaplan2.png
    # Buraya diğer uygulama içi görselleriniz gelebilir
    # - assets/images/logo.png # Eğer uygulama içinde kullanacaksanız

# UYGULAMA SİMGESİ (LAUNCHER ICON) AYARLARI BURADA
flutter_launcher_icons:
  android: true # Android için simge oluştur
  ios: true     # iOS için simge oluştur
  image_path: "assets/app_icon/app_icon.png" # <<-- Buraya simge dosyanızın YOLUNU YAZIN

  # İsteğe bağlı: Android Adaptive Icon ayarları (Modern Android için önerilir)
  # Eğer simgeniz şeffaf bir ön plan ve renkli/resimli bir arka plan istiyorsa
  # adaptive_icon_background: "#66BB6A"  # Tema renginiz gibi
  # adaptive_icon_foreground: "assets/app_icon/app_icon_foreground.png" # Şeffaf ön plan görseli
  # Basit ikon için sadece image_path yeterli olur.